root = "."
tmp_dir = "/tmp"

[build]
args_bin = []
bin = "true"
cmd = "bash ./build.sh && bash ./lint.sh"
delay = 0
exclude_dir = []
exclude_file = []
exclude_regex = []
exclude_unchanged = true
follow_symlink = true
full_bin = "true"
include_dir = []
include_ext = ["go", "mod", "sum"]
include_file = []
kill_delay = 100
poll = false
poll_interval = 100
post_cmd = []
pre_cmd = []
rerun = false
rerun_delay = 100
send_interrupt = false
stop_on_error = false

[color]
build = "yellow"
main = "magenta"
runner = "green"
watcher = "cyan"

[log]
main_only = false
time = false

[misc]
clean_on_exit = true

[screen]
clear_on_rebuild = false
keep_scroll = true
